### PR TITLE
Changed to sha1 based verification.

### PR DESCRIPTION
**Pull request by karrots**
Modified verification to use sha1 calculation on ESP and compare to local calculation. This has helped with issues where verification failed due to python interpreting the data.

### CODE REVIEW

**Comment by kmpm** [comment]
This looks great but I would like it to be optional to verify the files.
Please add an option to turn this on. Default should be off. I don't like the performance hit.
And, if this is a common thing, what could be done to make sure the error doesn't occur in the first place?

**Comment by kmpm** [comment]
could the corruption perhaps be due to #23

**Comment by kmpm** [comment]
Ooops, forgot about the existing verify option.
Still, do yo have an idea why this happens? (while I test the PR)

**Comment by karrots** [comment]
Couldn't ever figure out why Python was interpreting the data. The patch just replaces the existing verification method and is potentially faster especially on 9600 baud connections. 

That said I noticed after using it a bit more the verification can still fail. My only thought is line endings or something were changing after uploading. I should test on a newer NodeMCU code though as I was only seeing it on larger lua files which the large file issues are now fixed.

**Comment by kmpm** [comment]
I don't trust the sha1 hash in nodemcu. (running 0.9.6 build 2150704)
* I uploaded a file with verify and it failed verification. (jox1.lua)
* Downloaded the same file to another name (jox1.lua:jox2.lua)
* Checked the sha1sum of jox2.lua and it had the same signature as jox1.lua
It works on some files but not others...

**Comment by karrots** [comment]
You should test on a newer build from the dev branch. Personally I wouldn't
trust anything on old 0.9.x branches.

It still may not be perfect but for me it was more reliable than reading
things back.

**Comment by kmpm** [comment]
This will be merged as soon as as there is a published release of nodemcu-firmware that have a working crypto library.

Or add to the PR so that there is another verify option that uses sha1.

**Comment by karrots** [comment]
Which version was last tested? I believe the nodemcu crypto library is working fine its other underlying issues with the firmware. There were issues with files that approached 4k in size around the time this PR was opened. Those have now been fixed. My guess is this is why the char by char verification was also failing randomly. That and general file access was buggy. Most if not all of these have been fixed recently in the latest code base.

I'll rework the patch to be its own cli flag as per your other comment.

**Comment by kmpm** [comment]
Looks ok to me... Thanks

**Pull request merged**
